### ISSUE TITLE
the purity behind the curtain ...

### ISSUE THREAD

**Issue by trippingtarballs** [cullophid/date-fp#57]
> _A function that returns the current time or date, is impure because at different times it will yield different results—it refers to some global state._ – source, [wikipedia](https://en.m.wikipedia.org/wiki/Pure_function#Impure_functions)

Please could you add a high-level explanation to `README.md` that explains how `date-fp` enables the functionally-keen developer to safely work with date types whilst maintaining purity within their functions?

**Comment by cullophid** [comment]
HI Raj!
The idea is that date-fp only modifies existing dates. If you want to get the current date you can use new Date() just like normal, but this is not a part of date-fps api.
Currently date-fp is using localized date methods `date.getMonth()` etc. as opposed to `date.getUTCMonth()`. because of this date-fp is not currently pure.
I am working on a new version that makes date-fp 100% pure, and I will update the documentation acordingly.
We also welcome any PR for documentation/README :)
